name: Add Update Label Weekly

# Customization notes:
# ⓵ CUSTOMIZE: Change cron. Currently runs Fri 0700 UTC, exc. July and December
#    ⮡ You can compose a schedule here: https://crontab.cronhub.io/
# ⓶ CUSTOMIZE: Change to your project repo name
# ⓷ Use major version only to keep up to date

on:
  schedule:
    - cron: '0 7 * 1-6,8-11 5' # ⓵
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry-run mode without posting comments or updating issues'
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'

jobs:
  Add-Update-Label-Weekly:
    runs-on: ubuntu-latest
    if: github.repository == 'your-project/repo-name' # ⓶
    steps:
      - name: Generate token from GitHub App
        id: generate-app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.HFLA_GRAPHQL_APP_ID }}
          private-key: ${{ secrets.HFLA_GRAPHQL_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run workflow
        uses: hackforla/automate-the-org/add-update-label-weekly@v1 # ⓷ 
        with:
          github-token: ${{ steps.generate-app-token.outputs.token }}
          dry-run: ${{ github.event.inputs.dry-run || 'true' }}
